/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import model.Avatar;

/**
 *
 * @author Paulo
 */
public class JFramePrincipal extends javax.swing.JFrame {

    //Variável global para guardar dados da tabela, em qualquer situação
    List<Avatar> dadosDaTabela = new ArrayList<>();
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        //Colocando o ícone do programa
        ImageIcon img = new javax.swing.ImageIcon(getClass().getResource("/img/AvataresForFun-Icone_e_Logo_PNG.png"));
        this.setIconImage(img.getImage());
        //Atualziando tabela
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AvataresForFunPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        comboBox_criarSexo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spin_criarIdade = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        comboBox_criarEspecialidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comboBox_criarPersonalidade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_criarAltura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_criarNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_analiseNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_analiseId = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        spin_analiseIdade = new javax.swing.JSpinner();
        comboBox_analiseSexo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        comboBox_analiseEspecialidade = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboBox_analisePersonalidade = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_analiseAltura = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avatares For Fun");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("•Na guia \"Criar\" você pode criar seus avatres.");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ao Avatares For Fun");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bem-Vindo(a)");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("•Aqui é apenas um simples guia de apresentação.");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("•Na guia \"Analise\" você pode ver, atualizar e excluir avatres.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Página Inicial", jPanel2);

        comboBox_criarSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Idade");

        spin_criarIdade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBox_criarEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velocidade", "Esporte", "Agilidade", "Inteligência" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Personalidade");

        comboBox_criarPersonalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calmo(a)", "Frio(a)", "Irritado(a)", "Animado(a)", "Apressado(a)", "Alegre" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Altura");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Especialidade");

        txt_criarAltura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Nome");

        txt_criarNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Sexo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(429, 429, 429))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_criarPersonalidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBox_criarSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(txt_criarAltura)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_criarEspecialidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_criarNome)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(spin_criarIdade))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_criarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_criarIdade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_criarSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(txt_criarAltura))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_criarPersonalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_criarEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Criar", jPanel1);

        txt_analiseNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Altura");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Personalidade");

        jButton2.setText("Consulta por ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_analiseId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_analiseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_analiseIdActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Especialidade");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Idade", "Altura", "Sexo", "Personalidade", "Especialidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        spin_analiseIdade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        comboBox_analiseSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));

        jButton3.setText("Consulta por nome");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboBox_analiseEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velocidade", "Esporte", "Agilidade", "Inteligência" }));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Nome");

        comboBox_analisePersonalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calmo(a)", "Frio(a)", "Irritado(a)", "Animado(a)", "Apressado(a)", "Alegre" }));
        comboBox_analisePersonalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_analisePersonalidadeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Id");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Sexo");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Idade");

        txt_analiseAltura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Limpar Filtro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox_analisePersonalidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox_analiseEspecialidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_analiseNome)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(spin_analiseIdade))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 80, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBox_analiseSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_analiseAltura))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_analiseId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(172, 172, 172)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_analiseNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_analiseIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox_analiseSexo)
                    .addComponent(txt_analiseAltura))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_analisePersonalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBox_analiseEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_analiseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Analise", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void analise_setCamposPadrao(){
        //Voltando todos os campos ao padrão inicial
        txt_analiseId.setText("");
        txt_analiseNome.setText("");
        txt_analiseAltura.setText("");
        spin_analiseIdade.setValue(0);
        comboBox_analiseSexo.setSelectedItem("Masculino");
        comboBox_analisePersonalidade.setSelectedItem("Calmo(a)");
        comboBox_analiseEspecialidade.setSelectedItem("Velocidade");
    }
    
    public void criar_setCamposPadrao(){
        //Voltando todos os campos ao padrão inicial
        txt_criarNome.setText("");
        spin_criarIdade.setValue(0);
        txt_criarAltura.setText("");
        comboBox_criarSexo.setSelectedItem("Masculino");
        comboBox_criarPersonalidade.setSelectedItem("Calmo(a)");
        comboBox_criarEspecialidade.setSelectedItem("Velocidade");
    }
    
    public void atualizarTabela(){
        //Pegando o modelo da tabela (quantidade de linhas e colunas, e outras propriedades)
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        //Definindo número de linhas para a tabela. No caso retirando todas, como estamos setando 0
        modelo.setNumRows(0);
        
        //Criando uma lista, do tipo avatar, para pegar a lista de todos os avatares no banco de dados, utilizando o query
        List<Avatar> lista_avatar = entityManager1.createQuery("select a from Avatar a").getResultList();
        
        //Andando em toda a lista de avatares
        for(Avatar avatar : lista_avatar){
            //Adicionando linha na tabela. Como parâmetro do vetor de objetos, um atributo do objeto da tabela (no caso Avatar).
            //Os parâmetros são passados na ordem em que aparecerão na tabela.
            //Irá adicionar todos os avatares, pois o loop está rodando em toda a lista de avatares. O comando abaixo é para adicionar um linha
            //(no caso, adicona uma linha em cada vez que passa no loop).
            modelo.addRow(new Object[]{
                    avatar.getIdAvatar(),
                    avatar.getNome(),
                    avatar.getIdade(),
                    avatar.getAltura(),
                    avatar.getSexo(),
                    avatar.getPersonalidade(),
                    avatar.getEspecialidade()
            });
        }
        
        //Atualizando a variável global dadosDaTabela
        dadosDaTabela.clear();
        dadosDaTabela.addAll(lista_avatar);
    }
    
    //Este método irá servir para ver um avatar específico na tabela, quanto mexer em um, como remover e atualizar
    public void getAvatarEspecificoNaTabela(List<Avatar> listaResultados){
        //Sempre que houver uma consulta nova, todos os avatares estarão dentro da variável dados da tabela
        //Ela será limpada e adicionado os novos dados (avatares ainda existentes e atualizados) da tabela
        dadosDaTabela.clear();
        dadosDaTabela.addAll(listaResultados);
        //Pegando o modelo da tabela (quantidade de linhas e colunas, e outras propriedades)
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
        //Definindo número de linhas para a tabela. No caso retirando todas, como estamos setando 0
        modelo.setNumRows(0);
        
        //Andando em toda a lista de avatares
        for(Avatar avatar : listaResultados){
            //Adicionando linha na tabela. Como parâmetro do vetor de objetos, um atributo do objeto da tabela (no caso Avatar).
            //Os parâmetros são passados na ordem em que aparecerão na tabela.
            //Irá adicionar todos os avatares, pois o loop está rodando em toda a lista de avatares. O comando abaixo é para adicionar um linha
            //(no caso, adicona uma linha em cada vez que passa no loop).
            modelo.addRow(new Object[]{
                    avatar.getIdAvatar(),
                    avatar.getNome(),
                    avatar.getIdade(),
                    avatar.getAltura(),
                    avatar.getSexo(),
                    avatar.getPersonalidade(),
                    avatar.getEspecialidade()
            });
        }
    }
    
    private void comboBox_analisePersonalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_analisePersonalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_analisePersonalidadeActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Pegando a linha selecionada na tabela
        int linhaSelecionada = jTable2.getSelectedRow();
        //Verificando se há linha selecionada
        //Um vetor (ou lista) começa no índice 0, então, se não houver linha selecionada,
        //o getSelectedRow fica com -1
        if(linhaSelecionada >= 0){
            //Pegando a resposta de um JOptionPane de confirmação
            int resp = JOptionPane.showConfirmDialog(this, "Deseja, realmente, alterar este avatar?", "Confirmação", JOptionPane.YES_NO_OPTION);
            //Verificando se a opção selecionada foi sim
            if(resp == JOptionPane.YES_OPTION){
                //Pegando o avatar selecionado
                Avatar avatarSelecionado = dadosDaTabela.get(linhaSelecionada);
                //Guardando os novos valores dos atributos do avatar
                avatarSelecionado.setNome(txt_analiseNome.getText());
                avatarSelecionado.setIdade((Integer) spin_analiseIdade.getValue()); //Guardando o valor pego no spinner de idade, usando um casting para converter para inteiro
                avatarSelecionado.setAltura(Float.parseFloat(txt_analiseAltura.getText()));
                avatarSelecionado.setSexo(comboBox_analiseSexo.getSelectedItem().toString());
                avatarSelecionado.setPersonalidade(comboBox_analisePersonalidade.getSelectedItem().toString());
                avatarSelecionado.setEspecialidade(comboBox_analiseEspecialidade.getSelectedItem().toString());
                //Atualziando o avatar no banco de dados
                entityManager1.getTransaction().begin();
                entityManager1.merge(avatarSelecionado);
                entityManager1.getTransaction().commit();
                //Atualizando a tabela e voltando os campos ao padrão
                atualizarTabela();
                analise_setCamposPadrao();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_analiseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_analiseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_analiseIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Pegando id, que o usuário inserir para pesquisar
        int id = Integer.parseInt(txt_analiseId.getText());
        //Variável do tipo avatr, que guardará os dados do avatar, com o id inserido
        Avatar personagem = entityManager1.find(Avatar.class, id);
        //Mostrando informações do avatar, por meio de 1 JOptionPane
        JOptionPane.showMessageDialog(this, "Nome: " + personagem.getNome() + "\n" +
                                            "Idade: " + personagem.getIdade() + "\n" +
                                            "Altura: " + personagem.getAltura() + "\n" + 
                                            "Sexo: " + personagem.getSexo() + "\n" +
                                            "Personalidade: " + personagem.getPersonalidade() + "\n" +
                                            "Especialidade: " + personagem.getEspecialidade());
        //Limpando caixa de texto do id
        txt_analiseId.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Pegando a linha selecionada na tabela
        int linhaSelecionada = jTable2.getSelectedRow();
        //Verificando se há linha selecionada
        //Um vetor (ou lista) começa no índice 0, então, se não houver linha selecionada,
        //o getSelectedRow fica com -1
        if(linhaSelecionada >= 0){
            //Pegando a resposta de um JOptionPane de confirmação
            int resp = JOptionPane.showConfirmDialog(this, "Realmente, deseja remover o avatar?", "Confirmação", JOptionPane.YES_NO_OPTION);
            //Verificando se a opção selecionada foi sim
            if(resp == JOptionPane.YES_OPTION){
                //Pegando o avatar selecionado
                Avatar avatarSelecionado = dadosDaTabela.get(linhaSelecionada);
                //Removendo o avatar do banco de dados
                entityManager1.getTransaction().begin();
                entityManager1.remove(avatarSelecionado);
                entityManager1.getTransaction().commit();
                //Atualizando a tabela e voltando os campos ao padrão
                atualizarTabela();
                analise_setCamposPadrao();
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Criando objeto para guardar os dados da criação de um avatar
        Avatar personagem = new Avatar();
        //Guardadno os dados do avatar
        personagem.setNome(txt_criarNome.getText());
        String idadeValue = spin_criarIdade.getValue().toString(); //Para pegar o valor de um spinner foi necessário pegar em forma de string, primeiro
        personagem.setIdade(Integer.parseInt(idadeValue));
        personagem.setAltura(Float.parseFloat(txt_criarAltura.getText()));
        personagem.setSexo(comboBox_criarSexo.getSelectedItem().toString());
        personagem.setPersonalidade(comboBox_criarPersonalidade.getSelectedItem().toString());
        personagem.setEspecialidade(comboBox_criarEspecialidade.getSelectedItem().toString());
        
        //Fazendo a transação, para adicionar no banco de dados
        entityManager1.getTransaction().begin();
        entityManager1.persist(personagem);
        entityManager1.getTransaction().commit();
        
        //Alertando que o avatr for criado, limpando caixas de texto e atualizando a tabela de personagens, da guia analisar
        JOptionPane.showMessageDialog(this, "Avatar criado com sucesso!", "Avatar Criado", JOptionPane.INFORMATION_MESSAGE);
        criar_setCamposPadrao();
        atualizarTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Fazendo busca do avatar escolhido, por nome, pelo usuário.
        //Buscando onde (where) o nome do objeto a, declarado, no comando, for igual ao parâmetro nome
        Query consulta = entityManager1.createQuery("select a from Avatar a where a.nome = :nome");
        //Setando o valor para o parâmetro nome
        consulta.setParameter("nome", txt_analiseNome.getText());
        //Guardando a lista de avatares que a variável consulta, do tipo Query, pegar
        List<Avatar> listaResultados = consulta.getResultList();
        //Deixando, na tabela, apenas o avatar escolhido, por nome, pelo usuário
        getAvatarEspecificoNaTabela(listaResultados);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //O método atualizar tabela, atualiza a tabela, buscando todo o banco de dados
        atualizarTabela();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int linhaSelecionada = jTable2.getSelectedRow();
        //Verificando se a pessoa selecionou uma linha, pois pode ser que o usuário apenas clicou na tabela
        if(linhaSelecionada >= 0){
            //Pegando os dados do avatar na linha selecionada
            Avatar avatarSelecionado = dadosDaTabela.get(linhaSelecionada);
            txt_analiseNome.setText(avatarSelecionado.getNome());
            spin_analiseIdade.setValue(avatarSelecionado.getIdade());
            comboBox_analiseSexo.setSelectedItem(avatarSelecionado.getSexo());
            txt_analiseAltura.setText(avatarSelecionado.getAltura().toString());
            comboBox_analisePersonalidade.setSelectedItem(avatarSelecionado.getPersonalidade());
            comboBox_analiseEspecialidade.setSelectedItem(avatarSelecionado.getEspecialidade());
            txt_analiseId.setText(avatarSelecionado.getIdAvatar().toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox_analiseEspecialidade;
    private javax.swing.JComboBox<String> comboBox_analisePersonalidade;
    private javax.swing.JComboBox<String> comboBox_analiseSexo;
    private javax.swing.JComboBox<String> comboBox_criarEspecialidade;
    private javax.swing.JComboBox<String> comboBox_criarPersonalidade;
    private javax.swing.JComboBox<String> comboBox_criarSexo;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JSpinner spin_analiseIdade;
    private javax.swing.JSpinner spin_criarIdade;
    private javax.swing.JTextField txt_analiseAltura;
    private javax.swing.JTextField txt_analiseId;
    private javax.swing.JTextField txt_analiseNome;
    private javax.swing.JTextField txt_criarAltura;
    private javax.swing.JTextField txt_criarNome;
    // End of variables declaration//GEN-END:variables
}
